### ISSUE TITLE
Potential NPE in JavacTypeBinding

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#1013]
No steps to reproduce at the moment.
```
java.lang.NullPointerException: Cannot read field "kind" because "typeSymbol" is null
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.<init>(JavacTypeBinding.java:110)
	at org.eclipse.jdt.core.dom.JavacBindingResolver$Bindings$14.<init>(JavacBindingResolver.java:320)
	at org.eclipse.jdt.core.dom.JavacBindingResolver$Bindings.getTypeBinding(JavacBindingResolver.java:320)
	at org.eclipse.jdt.core.dom.JavacBindingResolver$Bindings.getTypeBinding(JavacBindingResolver.java:280)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveExpressionType(JavacBindingResolver.java:1248)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:636)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:656)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:662)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:667)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveConstructorImpl(JavacBindingResolver.java:1354)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.lambda$resolveConstructor$10(JavacBindingResolver.java:1325)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveCached(JavacBindingResolver.java:985)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveConstructor(JavacBindingResolver.java:1325)
	at org.eclipse.jdt.core.dom.ClassInstanceCreation.resolveConstructorBinding(ClassInstanceCreation.java:525)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightings.getBinding(SemanticHighlightings.java:2289)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightings$DeprecatedMemberHighlighting.consumes(SemanticHighlightings.java:1199)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler$PositionCollector.visit(SemanticHighlightingReconciler.java:250)
	at org.eclipse.jdt.core.dom.SimpleName.accept0(SimpleName.java:197)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.SimpleType.accept0(SimpleType.java:194)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.ClassInstanceCreation.accept0(ClassInstanceCreation.java:302)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:303)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:303)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:676)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:497)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:257)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler.reconcilePositions(SemanticHighlightingReconciler.java:477)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler.reconciled(SemanticHighlightingReconciler.java:427)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler$1.lambda$0(SemanticHighlightingReconciler.java:636)
	at org.eclipse.jdt.core.JavaCore.lambda$1(JavaCore.java:6166)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5694)
	at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5683)
	at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6150)
	at org.eclipse.jdt.core.JavaCore.runReadOnly(JavaCore.java:6165)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler$1.run(SemanticHighlightingReconciler.java:634)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment]
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/1098 fixes it (among others)
