### ISSUE TITLE
Freezes on exception during binding resolution

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#1035]
Often with Ctrl+C or Ctrl+X, I get
```
"main" #1 [77645] prio=6 os_prio=0 cpu=486005,00ms elapsed=2624,24s tid=0x00007fde8002f2c0 nid=77645 in Object.wait()  [0x00007fde857fa000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait0(java.base@23.0.1/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@23.0.1/Object.java:378)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:176)
	- locked <0x0000000619c56ba0> (a java.lang.Object)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:189)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:189)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:189)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction.getClipboardData(ClipboardOperationAction.java:488)
	at org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction.doCutCopyWithImportsOperation(ClipboardOperationAction.java:409)
	at org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction.internalDoOperation(ClipboardOperationAction.java:368)
	at org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction$$Lambda/0x00007fde043e7008.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction.run(ClipboardOperationAction.java:289)
```
and indeed, it seems to be waiting on... nothing; I cannot find in jstack any other thread doing JDT stuff.

**Comment by mickaelistria** [comment]
Looks like another case making the freeze highly probably is when trying to complete `final`

**Comment by mickaelistria** [comment]
After finally managing to enable more logging, I could see the following errors popping up before the CoreASTProvider gets stuck. This stack is probably enough to break the state of CoreASTProvider.

```
xception in thread "org.eclipse.jdt.internal.ui.text.JavaReconciler" java.lang.NullPointerException: Cannot read field "type" because "jcFieldAccess.sym" is null
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveExpressionType(JavacBindingResolver.java:1293)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:636)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:656)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:662)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:667)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveConstructorImpl(JavacBindingResolver.java:1372)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.lambda$resolveConstructor$10(JavacBindingResolver.java:1343)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveCached(JavacBindingResolver.java:999)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveConstructor(JavacBindingResolver.java:1343)
	at org.eclipse.jdt.core.dom.ClassInstanceCreation.resolveConstructorBinding(ClassInstanceCreation.java:525)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightings.getBinding(SemanticHighlightings.java:2289)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightings$DeprecatedMemberHighlighting.consumes(SemanticHighlightings.java:1199)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler$PositionCollector.visit(SemanticHighlightingReconciler.java:258)
	at org.eclipse.jdt.core.dom.SimpleName.accept0(SimpleName.java:197)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.SimpleType.accept0(SimpleType.java:194)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.ClassInstanceCreation.accept0(ClassInstanceCreation.java:302)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.VariableDeclarationFragment.accept0(VariableDeclarationFragment.java:238)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.VariableDeclarationStatement.accept0(VariableDeclarationStatement.java:253)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3360)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:676)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:497)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3383)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:257)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler.reconcilePositions(SemanticHighlightingReconciler.java:520)
	at org.eclipse.jdt.internal.ui.javaeditor.SemanticHighlightingReconciler.reconciled(SemanticHighlightingReconciler.java:469)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.reconciled(CompilationUnitEditor.java:1674)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconciled(JavaReconcilingStrategy.java:228)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconciled(JavaCompositeReconcilingStrategy.java:171)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:115)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
```

**Comment by mickaelistria** [comment]
So as this is likely to happen whenever there is an exception in the binding resolver, here are some tips that can help finding it:
* Start `eclipse` from command-line to get get more logging (some stacktraces are visible to System.err but not to the Eclipse log)
* Start `eclipse` with the right debug flags in eclipse.ini
* connect to it, put a breakpoint in `CoreASTProvider.getAST()` and when breakpoint is hit, in debug shell, do execute `JavaManipulationPlugin.DEBUG_AST_PROVIDER = true` to enable further logging.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/1176 tries to fix the particular NPE noted above

**Comment by mickaelistria** [comment]
While the fix for the exception listed above has made things more stable and freeze less frequent. Some freezes still occur occasionally. I suspect the reasons might be similar: an error in DOM conversion or binding resolution breaks reconciling threads and concurrency expectations.

**Comment by mickaelistria** [comment]
I'm seeing yet another occurrence of this issue. This time, it looks like a CompletionFailure is thrown somewhere by the compiler. However I didn't manage to find out when it is thrown to properly catch it before it crashes the ASTProvider. The issue with CompletionFailure is that they are constructed long before they're thrown, so I didn't find a good place to set a breakpoint and see the stack yet.

**Comment by mickaelistria** [comment]
So far, it's not been reproduced. Let's close (until it happens again)
