### ISSUE TITLE
dom-with-javac branch NPE

### ISSUE THREAD

**Issue by robstryker** [eclipse-jdtls/eclipse-jdt-core-incubator#141]
```
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "javac" is null
	at org.eclipse.jdt.core.dom.JavacConverter.convertToType(JavacConverter.java:1250)
	at org.eclipse.jdt.core.dom.JavacConverter.convertStatement(JavacConverter.java:1008)
	at org.eclipse.jdt.core.dom.JavacConverter.convertStatement(JavacConverter.java:958)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBlock(JavacConverter.java:1146)
	at org.eclipse.jdt.core.dom.JavacConverter.convertMethodDecl(JavacConverter.java:451)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:396)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:281)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:220)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:399)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:281)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:220)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:399)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:281)
	at org.eclipse.jdt.core.dom.JavacConverter.convertClassDecl(JavacConverter.java:220)
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:399)
	at org.eclipse.jdt.core.dom.JavacConverter.lambda$2(JavacConverter.java:142)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.jdt.core.dom.JavacConverter.populateCompilationUnit(JavacConverter.java:143)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.parse(JavacCompilationUnitResolver.java:154)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:107)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1246)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1158)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1125)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5762)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1125)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:873)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:186)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:245)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:275)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.hasSource(CoreASTProvider.java:393)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:269)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.ls.core.internal.handlers.SemanticTokensHandler.getAst(SemanticTokensHandler.java:83)
	at org.eclipse.jdt.ls.core.internal.handlers.SemanticTokensHandler.full(SemanticTokensHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$54(JDTLanguageServer.java:1176)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
```

Example file is https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/searcher/LocalRepositorySearcher.java

No test case created. But current code does have an apparent NPE weakness which I'll work on.

**Comment by mickaelistria** [comment]
I think this one has been fixed.
