### ISSUE TITLE
[javac] `Unsupported (ERROR) of typeclass com.sun.tools.javac.tree.JCTree$JCErroneous` on incomplete document

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#152]
Tested with jdt.ls. In an empty java file, simply type `c` (to get `class` snippet completion), the following exception is logged:

```
Problem with codeComplete for file:///Users/fbricon/Dev/souk/tychoarch/foo/bar/Test.java
Unsupported (ERROR) of typeclass com.sun.tools.javac.tree.JCTree$JCErroneous
java.lang.UnsupportedOperationException: Unsupported (ERROR) of typeclass com.sun.tools.javac.tree.JCTree$JCErroneous
	at org.eclipse.jdt.core.dom.JavacConverter.convertBodyDeclaration(JavacConverter.java:421)
	at org.eclipse.jdt.core.dom.JavacConverter.lambda$2(JavacConverter.java:145)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.jdt.core.dom.JavacConverter.populateCompilationUnit(JavacConverter.java:146)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.parse(JavacCompilationUnitResolver.java:160)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:107)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1246)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1158)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1125)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5762)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1125)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:873)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:191)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:245)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
	at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1581)
	at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1561)
	at org.eclipse.jdt.ls.core.internal.contentassist.SnippetCompletionProposal.getTypeDefinitionSnippets(SnippetCompletionProposal.java:478)
```

**Comment by mickaelistria** [comment]
Was fixed with #177
