### ISSUE TITLE
[javac] Unimplemented method 'isTypeVariable'

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#153]
Tested with jdt.ls, in a java file, like : 
```java
package foo.bar;

/**
 * Test
 */
public class Test {

  m|
}
```

type `m` to get the `main` method snippet, several exceptions are logged:

```
java.lang.UnsupportedOperationException: Unimplemented method 'isTypeVariable'
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.isTypeVariable(JavacTypeBinding.java:430)
	at org.eclipse.jdt.ls.core.internal.semantictokens.TokenType.getApplicableType(TokenType.java:108)
	at org.eclipse.jdt.ls.core.internal.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:315)
	at org.eclipse.jdt.core.dom.SimpleName.accept0(SimpleName.java:198)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3311)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3359)
	at org.eclipse.jdt.core.dom.SimpleType.accept0(SimpleType.java:195)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3311)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3359)
	at org.eclipse.jdt.core.dom.FieldDeclaration.accept0(FieldDeclaration.java:272)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3311)
	at org.eclipse.jdt.ls.core.internal.semantictokens.SemanticTokensVisitor.acceptNodeList(SemanticTokensVisitor.java:669)
```

**Comment by datho7561** [comment]
I've been trying to replicate this stacktrace so that I can make sure that when I implement isTypeVariable the stacktrace goes away, and I haven't been able to figure out how to build a version of jdt.ls that uses my local jdt.core.

**Comment by fbricon** [comment]
you need to 
- build jdt.core / javac locally with "mvn clean verify -DskipTests -Pp2-repo"
- modify https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target#L34 to point to your locally built repo, e.g. "file:///path/to/eclipse-jdt-core-incubator/repository/target/repository/"
- set JavaSE-21 in https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target#L71
- add ` <plugin id="org.eclipse.jdt.core.javac"/>` to https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.product/languageServer.product#L53

**Comment by datho7561** [comment]
Thanks!

**Comment by fbricon** [comment]
The error is no longer reproducible \o/
