### ISSUE TITLE
[javac] Unimplemented method 'getKey' in JavacMethodBinding

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#154]
Tested with jdt.ls, in a java file, like : 
```java
package foo.bar;

/**
 * Test
 */
public class Test {

  m|
}
```

type `m` to get the `main` method snippet, code action fails to compute with:

```
Caused by: java.lang.UnsupportedOperationException: Unimplemented method 'getKey'
	at org.eclipse.jdt.internal.javac.dom.JavacMethodBinding.getKey(JavacMethodBinding.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.JdtDomModels$LspMethodBinding.<init>(JdtDomModels.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.GenerateConstructorsHandler.lambda$0(GenerateConstructorsHandler.java:124)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at org.eclipse.jdt.ls.core.internal.handlers.GenerateConstructorsHandler.checkConstructorStatus(GenerateConstructorsHandler.java:124)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getGenerateConstructorsAction(SourceAssistProcessor.java:517)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getSourceActionCommands(SourceAssistProcessor.java:136)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:223)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:765)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
```

**Comment by fbricon** [comment]
The error is no longer reproducible \o/
