### ISSUE TITLE
[javac] Unimplemented method 'isNullType'

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#155]
Tested with jdt.ls, in a java file, like : 
```java
package foo.bar;

/**
 * Test
 */
public class Test {

  public static void main(String[] args) {
    S|
  }
}
```

type `S` to get the `String` completion snippet, code action fails to compute with:

```
java.lang.UnsupportedOperationException: Unimplemented method 'isNullType'
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.isNullType(JavacTypeBinding.java:397)
	at org.eclipse.jdt.internal.corext.refactoring.code.ExtractMethodAnalyzer.initReturnType(ExtractMethodAnalyzer.java:294)
	at org.eclipse.jdt.internal.corext.refactoring.code.ExtractMethodAnalyzer.checkInitialConditions(ExtractMethodAnalyzer.java:256)
	at org.eclipse.jdt.internal.corext.refactoring.code.ExtractMethodRefactoring.checkInitialConditions(ExtractMethodRefactoring.java:335)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.getExtractMethodProposal(RefactorProposalUtility.java:837)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.getExtractMethodCommandProposal(RefactorProposalUtility.java:296)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getExtractMethodProposal(RefactorProcessor.java:285)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getProposals(RefactorProcessor.java:143)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:187)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:765)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
```

Same exception seen in an other file (don't have the content anymore but I saved the stacktrace), while computing :

```
Caused by: java.lang.UnsupportedOperationException: Unimplemented method 'isNullType'
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.isNullType(JavacTypeBinding.java:397)
	at org.eclipse.jdt.internal.corext.dom.Bindings.createName(Bindings.java:251)
	at org.eclipse.jdt.internal.corext.dom.Bindings.getTypeQualifiedName(Bindings.java:194)
	at org.eclipse.jdt.internal.ui.text.correction.JavadocTagsBaseSubProcessor.addMissingJavadocCommentProposals(JavadocTagsBaseSubProcessor.java:241)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.JavadocTagsSubProcessor.addMissingJavadocCommentProposals(JavadocTagsSubProcessor.java:83)
```

**Comment by mickaelistria** [comment]
Was fixed with f85ab24e7c945bc2a18104ee1a206a8859fc5027
