### ISSUE TITLE
SearchPattern.findIndexMatches fails with NPE

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#156]
Tested with jdt.ls built against the javac branch, started in vscode-java without delegating completion to `javac`:
```
	params.push('--add-modules=ALL-SYSTEM',
				'--add-opens',
				'java.base/java.util=ALL-UNNAMED',
				'--add-opens',
				'java.base/java.lang=ALL-UNNAMED',
				// See https://github.com/redhat-developer/vscode-java/issues/2264
				// It requires the internal API sun.nio.fs.WindowsFileAttributes.isDirectoryLink() to check if a Windows directory is symlink.
				'--add-opens',
				'java.base/sun.nio.fs=ALL-UNNAMED',
				// Javac flags
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED',
				'--add-opens',
				'jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED',
				'-DICompilationUnitResolver=org.eclipse.jdt.core.dom.JavacCompilationUnitResolver',
				'-DCompilationUnit.DOM_BASED_OPERATIONS=true',
				// Javac based completion is useless for now
				// '-DCompilationUnit.codeComplete.DOM_BASED_OPERATIONS=true',
				'-DAbstractImageBuilder.compiler=org.eclipse.jdt.internal.javac.JavacCompiler'
				);
```				

 in a java file, like : 

```java
package foo.bar;

/**
 * Test
 */
public class Test {

  
  public static void main(String[] args) {
    
  }
}
```

Resolving codelens fails with: 

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(org.eclipse.jdt.internal.core.index.Index, org.eclipse.jdt.internal.core.search.IndexQueryRequestor, org.eclipse.jdt.core.search.SearchParticipant, org.eclipse.jdt.core.search.IJavaSearchScope, org.eclipse.core.runtime.IProgressMonitor)" because "pattern" is null
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.findIndexMatches(MatchLocator.java:307)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:240)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.execute(PatternSearchJob.java:120)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:384)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:235)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.findReferences(CodeLensHandler.java:147)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.resolve(CodeLensHandler.java:100)
```

I dunno if this is caused by the DOM-first changes or the Javac-based ones.

**Comment by fbricon** [comment]
This is fixed now, codelens works!
