### ISSUE TITLE
[javac] Unimplemented method `isSyntheticRecordMethod`

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#176]
In order to reproduce this issue, launch the javac branch in Eclipse, then create a new class file using the wizard. This should popup when you click "Create class"

**Comment by datho7561** [comment]
Stacktrace:

```
Root exception:
java.lang.UnsupportedOperationException: Unimplemented method 'isSyntheticRecordMethod'
	at org.eclipse.jdt.internal.javac.dom.JavacMethodBinding.isSyntheticRecordMethod(JavacMethodBinding.java:287)
	at org.eclipse.jdt.internal.corext.codemanipulation.StubUtility2Core.lambda$0(StubUtility2Core.java:1019)
	at org.eclipse.jdt.internal.corext.codemanipulation.StubUtility2Core.getMethodsIn(StubUtility2Core.java:913)
	at org.eclipse.jdt.internal.corext.codemanipulation.StubUtility2Core.getMethodsIn(StubUtility2Core.java:922)
	at org.eclipse.jdt.internal.corext.codemanipulation.StubUtility2Core.getUnimplementedMethods(StubUtility2Core.java:1023)
	at org.eclipse.jdt.internal.corext.codemanipulation.AddUnimplementedMethodsOperation.run(AddUnimplementedMethodsOperation.java:204)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.createInheritedMethods(NewTypeWizardPage.java:3350)
	at org.eclipse.jdt.ui.wizards.NewClassWizardPage.createTypeMembers(NewClassWizardPage.java:273)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.createType(NewTypeWizardPage.java:2859)
	at org.eclipse.jdt.internal.ui.wizards.NewClassCreationWizard.finishPage(NewClassCreationWizard.java:68)
	at org.eclipse.jdt.internal.ui.wizards.NewElementWizard.lambda$1(NewElementWizard.java:118)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:41)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2473)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:6074)
	at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:108)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```
