### ISSUE TITLE
Javac resolving modules sends IAE with SimpleJavaFileObject

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#275]
This might actually be more an issue in the JDK:
Currently, as it seems recommended by javax.tools.SimpleJavaFileObject , we do subclass it to inject the current content of the working copy (which may differ from what's on disk). This usually works fine, except when the project is modular as Javac tries to load the module (fine), but fails with 
```
 java.lang.IllegalArgumentException: /p/src/p/A.java
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.asPath(JavacFileManager.java:1195)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.contains(JavacFileManager.java:1121)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.checkSourceLocation(Modules.java:545)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:535)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:271)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:237)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolve(JavacBindingResolver.java:80)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveName(JavacBindingResolver.java:227)
	at org.eclipse.jdt.core.dom.Name.resolveBinding(Name.java:88)
```

The particular issue here is that javac seems to mandate that a PathFileObject is used while SimpleJavaFileObject is used.

A workaround for this particular case is to remove the module-info.java, to not go through `Modules.initModules`, but we will need modules to work eventually.

**Comment by mickaelistria** [comment]
This was fixed with #279
