### ISSUE TITLE
NPE in JavacCompilationUnitResolver

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#285]
The following code:

https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/blob/408c21d3c8a19456d44d0eb7a8bbb7f9e9eca77a/org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacCompilationUnitResolver.java#L233C1-L235C4

generates an exception (testing  https://github.com/eclipse/lemminx with the vsix at https://github.com/fbricon/vscode-java/releases/tag/wip-javac-24042024):

```
[Error - 4:18:25 PM] Apr 24, 2024, 4:18:25 PM An internal error occurred during: "Publish Diagnostics".
null
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:220)
	at java.base/java.util.Optional.of(Optional.java:113)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.findTargetDOM(JavacCompilationUnitResolver.java:234)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.findTargetDOM(JavacCompilationUnitResolver.java:240)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.lambda$9(JavacCompilationUnitResolver.java:177)
	at jdk.compiler/com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:730)
	at jdk.compiler/com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:699)
	at jdk.compiler/com.sun.tools.javac.util.Log.report(Log.java:664)
	at jdk.compiler/com.sun.tools.javac.util.AbstractLog.warning(AbstractLog.java:191)
	at jdk.compiler/com.sun.tools.javac.comp.Check.lambda$checkRedundantCast$1(Check.java:678)
	at jdk.compiler/com.sun.tools.javac.code.DeferredLintHandler.report(DeferredLintHandler.java:80)
	at jdk.compiler/com.sun.tools.javac.comp.Check.checkRedundantCast(Check.java:676)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitTypeCast(Attr.java:4096)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:2204)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitParens(Attr.java:3945)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:2033)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:4365)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2582)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2612)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1816)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:4365)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2582)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2612)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1816)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:2476)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1728)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:736)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:755)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitLambda(Attr.java:3198)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1993)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredType.complete(DeferredAttr.java:316)
	at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:355)
	at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrNode.process(DeferredAttr.java:808)
	at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrContext.complete(DeferredAttr.java:623)
	at jdk.compiler/com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:208)
	at jdk.compiler/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:618)
	at jdk.compiler/com.sun.tools.javac.comp.Resolve.checkMethod(Resolve.java:657)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.checkMethod(Attr.java:4904)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:4695)
	at jdk.compiler/com.sun.tools.javac.comp.AttrRecover.basicMethodInvocationRecovery(AttrRecover.java:224)
	at jdk.compiler/com.sun.tools.javac.comp.AttrRecover.recoverMethodInvocation(AttrRecover.java:214)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.checkMethodIdInternal(Attr.java:4598)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.checkId(Attr.java:4588)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:4481)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2582)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2612)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1816)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitExec(Attr.java:2327)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1603)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:736)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:755)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1440)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1092)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:736)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1229)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:916)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:736)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5615)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5503)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5327)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:5266)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1366)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1339)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolve(JavacBindingResolver.java:83)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolvePackage(JavacBindingResolver.java:267)
	at org.eclipse.jdt.core.dom.PackageDeclaration.resolveBinding(PackageDeclaration.java:324)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.resolveBindings(JavacCompilationUnitResolver.java:132)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:156)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:209)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:109)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:805)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1491)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:332)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:295)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:777)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment]
This  happens when the compiler throws errors about another file.

**Comment by mickaelistria** [comment]
fixed with https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/288
