### ISSUE TITLE
NPE in JavacBindingResolver.symbol

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#301]
JDT.LS fails at finding links in https://github.com/eclipse/lemminx/blob/ef5d223a96a9390819b8f9f9378092d7eeeaa021/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/uriresolver/CacheResourcesManagerTest.java#L42

```
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:220)
	at java.base/java.util.Optional.of(Optional.java:113)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.symbol(JavacBindingResolver.java:121)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.lambda$0(JavacBindingResolver.java:78)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1134)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolve(JavacBindingResolver.java:77)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolvePackage(JavacBindingResolver.java:255)
	at org.eclipse.jdt.core.dom.PackageDeclaration.resolveBinding(PackageDeclaration.java:324)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.resolveBindings(JavacCompilationUnitResolver.java:129)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:153)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
	at org.eclipse.jdt.internal.core.CompilationUnit.getOrBuildAST(CompilationUnit.java:552)
	at org.eclipse.jdt.internal.codeassist.DOMCodeSelector.codeSelect(DOMCodeSelector.java:106)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:527)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:519)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:1036)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementAtSelection(JDTUtils.java:1017)
	at org.eclipse.jdt.ls.core.internal.handlers.FindLinksHandler.findLinks(FindLinksHandler.java:46)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$11(JDTLanguageServer.java:728)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
```

https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/blob/48bf93e8d4886a4e0a5be565a3647dcc7a1cf0ca/org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacBindingResolver.java#L121

**Comment by mickaelistria** [comment]
I can reproduce it. The symbol that's not resolved is `org.junit.jupiter.api.Assertions.assertNotNull`

**Comment by mickaelistria** [comment]
There are a few issues involved: one is that we should use `ofNullable` here, the other is the we don't implement `JavacBindingResolve.resolveImport()` and another is that the JCFieldDeclaration don't seem to set symbol for static methods, so we need to get the type binding and then resolve the declaared method from it.

**Comment by fbricon** [comment]
another likely `ofNullable` candidate
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/blob/dom-with-javac/org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacBindingResolver.java#L118
