### ISSUE TITLE
[javac] Javadoc doesn't show on annotated methods

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#362]
Take a look at Fred's snippet here: https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/321

When running in Eclipse, hover over the word `Annotated`. Normally, a blank tooltip should appear, but instead I get a stacktrace:

```
!ENTRY org.eclipse.jface.text 4 0 2024-05-03 15:49:19.145
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IJavaElement.getHandleIdentifier()" because "element" is null
	at org.eclipse.jdt.internal.ui.viewsupport.CoreJavaElementLinks.createURIAsUri(CoreJavaElementLinks.java:109)
	at org.eclipse.jdt.internal.ui.viewsupport.CoreJavaElementLinks.createURI(CoreJavaElementLinks.java:97)
	at org.eclipse.jdt.internal.ui.viewsupport.CoreJavaElementLinks.createURI(CoreJavaElementLinks.java:79)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementLinks.createURI(JavaElementLinks.java:678)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.addAnnotation(JavadocHover.java:1301)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getAnnotations(JavadocHover.java:1238)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.addAnnotations(JavadocHover.java:1191)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo(JavadocHover.java:796)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.internalGetHoverInfo(JavadocHover.java:717)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo2(JavadocHover.java:709)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

**Comment by fbricon** [comment]
I can't reproduce this error in vscode-java after #321 was merged. @datho7561 can you?

**Comment by fbricon** [comment]
the title mentions "method" but my sample was an annotated class

**Comment by datho7561** [comment]
Can't reproduce. One of my fixes might have addressed this.
