### ISSUE TITLE
[javac] ClassCastException: class o.e.j.c.d.Block is not an instance of class o.e.j.c.d.AbstractUnnamedTypeDeclaration when opening String.class

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#369]
After opening String.class in vscode-java, I'm seeing this error:

```

[Trace - 3:45:06 PM] Sending request 'codeLens/resolve - (57)'.
Params: {
    "range": {
        "start": {
            "line": 110,
            "character": 19
        },
        "end": {
            "line": 110,
            "character": 25
        }
    },
    "data": [
        "jdt://contents/rt.jar/java.lang/String.class?=org.eclipse.lemminx/%5C/Users%5C/fbricon%5C/.sdkman%5C/candidates%5C/java%5C/8.0.402-zulu%5C/zulu-8.jdk%5C/Contents%5C/Home%5C/jre%5C/lib%5C/rt.jar=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/javase%5C/8%5C/docs%5C/api%5C/=/=/maven.pomderived=/true=/%3Cjava.lang(String.class",
        {
            "line": 110,
            "character": 19
        },
        "references"
    ]
}


[Trace - 3:45:07 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "May 6, 2024, 3:45:07 PM Unsupported ; of typeclass com.sun.tools.javac.tree.JCTree$JCSkip"
}


[Error - 3:45:07 PM] May 6, 2024, 3:45:07 PM Unsupported ; of typeclass com.sun.tools.javac.tree.JCTree$JCSkip
[Trace - 3:45:07 PM] Received notification 'telemetry/event'.
Params: {
    "name": "java.ls.error",
    "properties": {
        "message": "Unsupported ; of typeclass com.sun.tools.javac.tree.JCTree$JCSkip"
    }
}


May 06, 2024 3:45:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.ClassCastException: class org.eclipse.jdt.core.dom.Block is not an instance of class org.eclipse.jdt.core.dom.AbstractUnnamedTypeDeclaration
java.util.concurrent.CompletionException: java.lang.ClassCastException: class org.eclipse.jdt.core.dom.Block is not an instance of class org.eclipse.jdt.core.dom.AbstractUnnamedTypeDeclaration
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.ClassCastException: class org.eclipse.jdt.core.dom.Block is not an instance of class org.eclipse.jdt.core.dom.AbstractUnnamedTypeDeclaration
	at org.eclipse.jdt.core.dom.ASTNode.checkNewChild(ASTNode.java:2734)
	at org.eclipse.jdt.core.dom.ASTNode$NodeList.add(ASTNode.java:1675)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at org.eclipse.jdt.core.dom.JavacConverter.populateCompilationUnit(JavacConverter.java:162)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.parse(JavacCompilationUnitResolver.java:341)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:254)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:219)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:245)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:275)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.toRange(JDTUtils.java:907)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.toLocation(JDTUtils.java:809)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler$1.acceptSearchMatch(CodeLensHandler.java:160)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2198)
	at org.eclipse.jdt.internal.core.search.matching.TypeReferenceLocator.matchReportReference(TypeReferenceLocator.java:536)
	at org.eclipse.jdt.internal.core.search.matching.TypeReferenceLocator.matchReportReference(TypeReferenceLocator.java:365)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2969)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3276)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2871)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2053)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1366)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1403)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1546)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:134)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.findReferences(CodeLensHandler.java:147)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.resolve(CodeLensHandler.java:100)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$17(JDTLanguageServer.java:819)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more

```

**Comment by mickaelistria** [comment]
I cannot reproduce it with current snapshots. Can you please retry?

**Comment by fbricon** [comment]
Can't reproduce either with the latest build.
