### ISSUE TITLE
[javac] IllegalArgumentException in com.sun.tools.javac.api.JavacTaskImpl.analyze

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#382]
The following code 
```
public class MyClass {
    1e
}
```

causes the javac compiler to freak out:

```
[Error - 5:16:34 PM] Request codeLens/resolve failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.IllegalStateException: java.lang.IllegalArgumentException
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolve(JavacBindingResolver.java:74)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveType(JavacBindingResolver.java:165)
	at org.eclipse.jdt.core.dom.TypeDeclaration.internalResolveBinding(TypeDeclaration.java:832)
	at org.eclipse.jdt.core.dom.AbstractTypeDeclaration.resolveBinding(AbstractTypeDeclaration.java:138)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.resolveBindings(JavacCompilationUnitResolver.java:224)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:246)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
	at org.eclipse.jdt.internal.core.CompilationUnit.getOrBuildAST(CompilationUnit.java:552)
	at org.eclipse.jdt.internal.codeassist.DOMCodeSelector.codeSelect(DOMCodeSelector.java:106)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:527)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:519)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:1042)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementAtSelection(JDTUtils.java:1023)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.resolve(CodeLensHandler.java:97)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$17(JDTLanguageServer.java:804)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
Caused by: java.lang.IllegalArgumentException
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.<init>(JCDiagnostic.java:643)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.<init>(JCDiagnostic.java:623)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.create(JCDiagnostic.java:300)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.error(JCDiagnostic.java:113)
	at jdk.compiler/com.sun.tools.javac.util.AbstractLog.error(AbstractLog.java:145)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.lexError(JavaTokenizer.java:216)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanFraction(JavaTokenizer.java:682)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanFractionAndSuffix(JavaTokenizer.java:694)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanNumber(JavaTokenizer.java:762)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.readToken(JavaTokenizer.java:999)
	at jdk.compiler/com.sun.tools.javac.parser.Scanner.nextToken(Scanner.java:117)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.getPositionUsingScanner(JavacProblemConverter.java:97)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.getDiagnosticPosition(JavacProblemConverter.java:73)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.createJavacProblem(JavacProblemConverter.java:46)
	at org.eclipse.jdt.core.dom.JavacConverter.convertDiagnostic(JavacConverter.java:2358)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.lambda$14(JavacCompilationUnitResolver.java:274)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.lambda$13(JavacCompilationUnitResolver.java:271)
	at jdk.compiler/com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:730)
	at jdk.compiler/com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:711)
	at jdk.compiler/com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.reportDeferredDiagnostics(Log.java:171)
	at jdk.compiler/com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.reportDeferredDiagnostics(Log.java:163)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1199)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1178)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:399)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
	... 28 more
```

Executing `javac MyClass.java` yields:

```
javac MyClass.java
MyClass.java:2: error: malformed floating-point literal
    1e
    ^
1 error
```

**Comment by mickaelistria** [comment]
For the same class, I get some deeper error:
```
An exception has occurred in the compiler (22-ea). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.IllegalArgumentException
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.<init>(JCDiagnostic.java:643)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.<init>(JCDiagnostic.java:623)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.create(JCDiagnostic.java:300)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.error(JCDiagnostic.java:113)
	at jdk.compiler/com.sun.tools.javac.util.AbstractLog.error(AbstractLog.java:145)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.lexError(JavaTokenizer.java:216)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanFraction(JavaTokenizer.java:682)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanFractionAndSuffix(JavaTokenizer.java:694)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanNumber(JavaTokenizer.java:762)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.readToken(JavaTokenizer.java:999)
	at jdk.compiler/com.sun.tools.javac.parser.Scanner.nextToken(Scanner.java:117)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.getPositionUsingScanner(JavacProblemConverter.java:99)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.getDiagnosticPosition(JavacProblemConverter.java:74)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.createJavacProblem(JavacProblemConverter.java:47)
	at org.eclipse.jdt.core.dom.JavacConverter.convertDiagnostic(JavacConverter.java:2355)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.lambda$14(JavacCompilationUnitResolver.java:275)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.lambda$13(JavacCompilationUnitResolver.java:272)
	at jdk.compiler/com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:730)
	at jdk.compiler/com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:711)
	at jdk.compiler/com.sun.tools.javac.util.Log.report(Log.java:664)
	at jdk.compiler/com.sun.tools.javac.util.AbstractLog.error(AbstractLog.java:145)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.lexError(JavaTokenizer.java:216)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanFraction(JavaTokenizer.java:682)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanFractionAndSuffix(JavaTokenizer.java:694)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.scanNumber(JavaTokenizer.java:762)
	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.readToken(JavaTokenizer.java:999)
	at jdk.compiler/com.sun.tools.javac.parser.Scanner.nextToken(Scanner.java:117)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.nextToken(JavacParser.java:317)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.accept(JavacParser.java:510)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.accept(JavacParser.java:502)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classInterfaceOrRecordBody(JavacParser.java:4560)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:4271)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.classOrRecordOrInterfaceOrEnumDeclaration(JavacParser.java:4218)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:4207)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:4014)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:652)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:629)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:689)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1043)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler$InitialFileParser.parse(JavaCompiler.java:1980)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1030)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.parseInternal(JavacTaskImpl.java:258)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.parse(JavacTaskImpl.java:248)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.parse(JavacCompilationUnitResolver.java:313)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:243)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:219)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:245)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
	at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1317)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:183)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:109)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:805)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1491)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

**Comment by mickaelistria** [comment]
The issue comes from JavacProblemConverter.getPositionUsingScanner using a new context instead of reusing the one that was used for parsing.
