### ISSUE TITLE
NPE in tests: `Cannot invoke "com.sun.tools.javac.code.Type.getTypeArguments()" because "this.type" is null`

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#414]
Ex with ASTConverterTest2.test0409
```
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getTypeArguments()" because "this.type" is null
	at jdk.compiler/com.sun.tools.javac.code.Symbol.getTypeParameters(Symbol.java:749)
	at org.eclipse.jdt.internal.javac.dom.JavacMethodBinding.getKey(JavacMethodBinding.java:171)
	at org.eclipse.jdt.internal.javac.dom.JavacVariableBinding.getKey(JavacVariableBinding.java:149)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.canonicalize(JavacBindingResolver.java:534)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.getBinding(JavacBindingResolver.java:252)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveName(JavacBindingResolver.java:342)
	at org.eclipse.jdt.core.dom.Name.resolveBinding(Name.java:88)
	at org.eclipse.jdt.core.tests.dom.BindingsCollectorVisitor.endVisit(BindingsCollectorVisitor.java:334)
	at org.eclipse.jdt.core.dom.SimpleName.accept0(SimpleName.java:199)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3387)
	at org.eclipse.jdt.core.dom.VariableDeclarationFragment.accept0(VariableDeclarationFragment.java:234)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3410)
	at org.eclipse.jdt.core.dom.VariableDeclarationStatement.accept0(VariableDeclarationStatement.java:253)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3410)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3387)
	at org.eclipse.jdt.core.dom.Initializer.accept0(Initializer.java:236)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3410)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:489)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3410)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3339)
	at org.eclipse.jdt.core.tests.dom.ASTConverterTest2.test0409(ASTConverterTest2.java:316)
```

**Comment by mickaelistria** [comment]
Looks like this happens whenever there is some variable in class initializer blocks, eg
```java
class A {
  {
    int n;
  }
}
```
