### ISSUE TITLE
[javac] "error: release version 1.8 not supported" in JavacCompilationUnitResolver.parse

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#423]
Running jdt.ls tests against the Javac branch, a lot of tests are failing with :

```
java.lang.IllegalArgumentException: error: release version 1.8 not supported
00:59:21 	at jdk.compiler/com.sun.tools.javac.main.Arguments.reportDiag(Arguments.java:904)
00:59:21 	at jdk.compiler/com.sun.tools.javac.main.Arguments.handleReleaseOptions(Arguments.java:314)
00:59:21 	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:353)
00:59:21 	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:249)
00:59:21 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:191)
00:59:21 	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.parse(JavacCompilationUnitResolver.java:312)
00:59:21 	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:248)
00:59:21 	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
00:59:21 	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
00:59:21 	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
00:59:21 	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
00:59:21 	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
00:59:21 	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
00:59:21 	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:219)
00:59:21 	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:245)
00:59:21 	at org.eclipse.jdt.internal.core.SourceRefElement.generateInfos(SourceRefElement.java:128)
00:59:21 	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
00:59:21 	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
00:59:21 	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
00:59:21 	at org.eclipse.jdt.internal.core.JavaElement.exists(JavaElement.java:211)
00:59:21 	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelComposerCore.appendMethodPrependedTypeParams(JavaElementLabelComposerCore.java:321)
00:59:21 	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelComposerCore.appendMethodLabel(JavaElementLabelComposerCore.java:252)
00:59:21 	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelComposerCore.appendElementLabel(JavaElementLabelComposerCore.java:174)
00:59:21 	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelsCore.getElementLabel(JavaElementLabelsCore.java:432)
00:59:21 	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelsCore.getElementLabel(JavaElementLabelsCore.java:420)
00:59:21 	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeSignature(HoverInfoProvider.java:254)
```

See https://ci.eclipse.org/ls/job/jdt-ls-javac/3/console. e.g. [JavadocContentTest](https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/ecc87c687682462d61843b67e69ec5bb5c84e08a/org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentTest.java#L43) imports the [`eclipse/hello`](https://github.com/eclipse-jdtls/eclipse.jdt.ls/tree/ecc87c687682462d61843b67e69ec5bb5c84e08a/org.eclipse.jdt.ls.tests/projects/eclipse/hello) project

**Comment by fbricon** [comment]
I think the proper release flag to pass needs to be `8`, instead of `1.8`

**Comment by fbricon** [comment]
I believe this code is wrong: 
https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/blob/9c3ef4cbebafea02065ba2e7249714659e83b697/org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/JavacUtils.java#L65-L69

it should use the release value, instead of the compliance, to set the release flag. If release is not set, then use source and target flags instead

**Comment by testforstephen** [comment]
The release value in JDT preference is a boolean value, cannot use it directly. We should convert the version format (e.g. 1.8) to 8 before passing it to javac. It applies to `-source` and `-target` of javac as well.
