### ISSUE TITLE
[javac] "Error in Java Model" with code referencing interface

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#487]
Opening https://github.com/spring-projects/spring-petclinic with [vscode-java](https://github.com/fbricon/vscode-java/releases/tag/javac-prototype) embedding the javac bits, I get multiple similar errors when opening files, like [VetRepository.java](https://github.com/spring-projects/spring-petclinic/blob/main/src/main/java/org/springframework/samples/petclinic/vet/VetRepository.java):

```
[Error - 10:40:41 AM] Jun 13, 2024, 10:40:41 AM findAll(org.springframework.data.domain.Pageable) [in VetRepository [in VetRepository.java [in org.springframework.samples.petclinic.vet [in src/main/java [in spring-petclinic]]]]] does not exist
findAll(org.springframework.data.domain.Pageable) [in VetRepository [in VetRepository.java [in org.springframework.samples.petclinic.vet [in src/main/java [in spring-petclinic]]]]] does not exist
Java Model Exception: Error in Java Model (code 969): findAll(org.springframework.data.domain.Pageable) [in VetRepository [in VetRepository.java [in org.springframework.samples.petclinic.vet [in src/main/java [in spring-petclinic]]]]] does not exist
    at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:562)
    at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:605)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
    at org.eclipse.jdt.internal.core.SourceMethod.getParameterNames(SourceMethod.java:141)
    at [org.eclipse.jdt.ls](http://org.eclipse.jdt.ls/).core.internal.handlers.InlayHintVisitor.getParameterNames(InlayHintVisitor.java:215)
    at [org.eclipse.jdt.ls](http://org.eclipse.jdt.ls/).core.internal.handlers.InlayHintVisitor.resolveInlayHints(InlayHintVisitor.java:165)
    at [org.eclipse.jdt.ls](http://org.eclipse.jdt.ls/).core.internal.handlers.InlayHintVisitor.visit(InlayHintVisitor.java:87)
    at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:220)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3391)
    at org.eclipse.jdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:128)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
    at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3391)
    at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:677)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
    at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:498)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
    at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
    at [org.eclipse.jdt.ls](http://org.eclipse.jdt.ls/).core.internal.handlers.InlayHintsHandler.inlayHint(InlayHintsHandler.java:81)
    at [org.eclipse.jdt.ls](http://org.eclipse.jdt.ls/).core.internal.handlers.JDTLanguageServer.lambda$56(JDTLanguageServer.java:1184)
    at [org.eclipse.jdt.ls](http://org.eclipse.jdt.ls/).core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by mickaelistria** [comment]
Looking at the stacktrace and trying to reproduce in my IDE, I don't see an obvious reason for this crash.
Could it be that the Java Model is not yes fully resolved/reconciled at the instant you're asking for it?

**Comment by fbricon** [comment]
The problem is not linked to outside jars. I managed to reproduce with a simple setup in vscode (which triggers the inlay hints request):
Given this interface :
```java
public interface MyRunner {

    void execute(Runnable runnable);

}
```

The exception occurs when opening a class calling its method:
```java
public class ModelProblem {
    MyRunner myClass;

    public void delegate(Runnable runnable) {
        myClass.execute(runnable);
    }
}
```


```
[Error - 3:38:08 PM] Jun 14, 2024, 3:38:08 PM execute(java.lang.Runnable) [in MyRunner [in [Working copy] MyRunner.java [in <default> [in _ [in modelException_51f08b73]]]]] does not exist
execute(java.lang.Runnable) [in MyRunner [in [Working copy] MyRunner.java [in <default> [in _ [in modelException_51f08b73]]]]] does not exist
Java Model Exception: Error in Java Model (code 969): execute(java.lang.Runnable) [in MyRunner [in [Working copy] MyRunner.java [in <default> [in _ [in modelException_51f08b73]]]]] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:562)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:605)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.SourceMethod.getParameterNames(SourceMethod.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.InlayHintVisitor.getParameterNames(InlayHintVisitor.java:215)
	at org.eclipse.jdt.ls.core.internal.handlers.InlayHintVisitor.resolveInlayHints(InlayHintVisitor.java:165)
	at org.eclipse.jdt.ls.core.internal.handlers.InlayHintVisitor.visit(InlayHintVisitor.java:87)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:220)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3391)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3391)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:677)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:498)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.ls.core.internal.handlers.InlayHintsHandler.inlayHint(InlayHintsHandler.java:81)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$56(JDTLanguageServer.java:1184)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by fbricon** [comment]
Even simpler reproducer in a single class/method:

```
    void execute(Runnable runnable) {
        runnable.equals(this);
    }
 ``` 
 
 ```
 [Error - 3:55:47 PM] Jun 14, 2024, 3:55:47 PM equals(java.lang.Object) [in Runnable [in Runnable.class [in java.lang [in <module:java.base>]]]] does not exist
equals(java.lang.Object) [in Runnable [in Runnable.class [in java.lang [in <module:java.base>]]]] does not exist
Java Model Exception: Error in Java Model (code 969): equals(java.lang.Object) [in Runnable [in Runnable.class [in java.lang [in <module:java.base>]]]] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:562)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:605)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.BinaryMethod.getParameterNames(BinaryMethod.java:297)
	at org.eclipse.jdt.ls.core.internal.handlers.InlayHintVisitor.getParameterNames(InlayHintVisitor.java:215)
 
 ```

**Comment by mickaelistria** [comment]
FWIW, those are 2 distinct errors, the later is caused by JavacTypeBinding.getSuperClass() not return java.lang.Object when expected; the 1st one I'm investigating.
