### ISSUE TITLE
Name DOM -> IVariableBinding -> ILocalVariable seems to resolve incorrectly with some lambdas

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#51]
```java
// Inspired from test429738, [1.8][search] Find Declarations (Ctrl + G) shows no result for type-less lambda parameter
public void test429738() throws CoreException {
	org.eclipse.jdt.internal.core.CompilationUnit workingCopy = (org.eclipse.jdt.internal.core.CompilationUnit) getWorkingCopy("/JavaSearchBugs/src/b400905/X.java", "");
	this.workingCopies = new ICompilationUnit[] { workingCopy };
	workingCopy.getBuffer().setContents("""
		@FunctionalInterface
		interface Foo {
			int foo(int x);
		}
		public class X {
			// Select 'x' in lambda body and press Ctrl+G.
			Foo f1= x -> /* here*/ x; //[1]
			Foo f2= (int x) -> x; //[2]
		}
		""");

	String selection = "/* here*/ x";
	int start = workingCopy.getSource().indexOf(selection) + 10;
	int length = 1;
	assertEquals("x", workingCopy.getSource().substring(start, start + length));
	CompilationUnit dom = workingCopy.makeConsistent(AST.getJLSLatest(), true, 0, new HashMap<>(), null);
	SimpleName name = (SimpleName)NodeFinder.perform(dom, start, 1);
	IVariableBinding binding = (IVariableBinding)name.resolveBinding();
	ILocalVariable local = (ILocalVariable)binding.getJavaElement();
	search(local, DECLARATIONS, EXACT_RULE);
	assertSearchResults(
			"src/b400905/X.java int b400905.X.f1:<lambda #1>.foo(int).x [x] EXACT_MATCH");
}
```
This cause a bunch of other failures as the wrong ILocalVariable seems to be resolved
```
junit.framework.ComparisonFailure: Unexpected search results.
----------- Expected ------------
src/b400905/X.java int b400905.X.f1:<lambda #1>.foo(int).x [x] EXACT_MATCH
------------ but was ------------
src/b400905/X.java int b400905.Foo.foo(int).x [x] EXACT_MATCH
---------------------- ----------
 expected:<.../X.java int b400905.[X.f1:<lambda #1>].foo(int).x [x] EXAC...> but was:<.../X.java int b400905.[Foo].foo(int).x [x] EXAC...>
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
	at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:948)
	at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:906)
	at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:903)
	at org.eclipse.jdt.core.tests.model.JavaSearchBugs8Tests.test429738(JavaSearchBugs8Tests.java:3448)
```

This might be an upstream JDT issue, however I didn't yet had the opportunity to try to confirm it with vanilla JDT before reporting it. If it appears to be reproducible with plain JDT, the issue should be cloned, and fixed, upstream.

**Comment by mickaelistria** [comment]
Confirmed and reported upstream as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2047
