### ISSUE TITLE
[javac] StackOverflow in Type Binding

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#510]
Given this code:

```java
public class ModelProblem {
    RunMachine myClass;

    public void delegate(Runnable runner) {
        myClass.execute(runner);
    }

    public static class RunMachine {
        void execute(Runnable runnable){
        };
    }
}
```

With this morning build of vscode-java against [3f96312](https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/commit/3f96312371d4c591474d3ca6e158b9242c2d18f9), a StackOverflow is triggered when putting the cursor on `runner`, on line 5:

```
Caused by: java.lang.StackOverflowError
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.<init>(JavacTypeBinding.java:71)
	at org.eclipse.jdt.core.dom.JavacBindingResolver$Bindings$7.<init>(JavacBindingResolver.java:129)
	at org.eclipse.jdt.core.dom.JavacBindingResolver$Bindings.getTypeBinding(JavacBindingResolver.java:129)
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.lambda$13(JavacTypeBinding.java:329)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:622)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:631)
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.getDeclaredTypes(JavacTypeBinding.java:330)
	at org.eclipse.jdt.internal.corext.codemanipulation.ContextSensitiveImportRewriteContext.containingDeclaration(ContextSensitiveImportRewriteContext.java:186)
	at org.eclipse.jdt.internal.corext.codemanipulation.ContextSensitiveImportRewriteContext.findInContext(ContextSensitiveImportRewriteContext.java:129)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.internalAddImport(ImportRewrite.java:1216)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.createBaseType(ImportRewrite.java:1519)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.internalAddImport(ImportRewrite.java:1587)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.addImport(ImportRewrite.java:1027)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.addAnnotation(ImportRewrite.java:678)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.annotateList(ImportRewrite.java:1472)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.createBaseType(ImportRewrite.java:1530)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.internalAddImport(ImportRewrite.java:1587)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.addImport(ImportRewrite.java:1027)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.addAnnotation(ImportRewrite.java:678)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.annotateList(ImportRewrite.java:1472)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.createBaseType(ImportRewrite.java:1530)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.internalAddImport(ImportRewrite.java:1587)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.addImport(ImportRewrite.java:1027)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.addAnnotation(ImportRewrite.java:678)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.annotateList(ImportRewrite.java:1472)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.createBaseType(ImportRewrite.java:1530)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.internalAddImport(ImportRewrite.java:1587)
```

**Comment by mickaelistria** [comment]
Is this still happening?
