### ISSUE TITLE
[javac] NPEs thrown when class doesn't set proper package

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#543]
In a `foo/bar` package, create a package-less class, such as:

```java
public class Toto{
}
```

WIth VS Code, when clicking on `Toto`, the request to get code actions will throw a bunch of errors like:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IMember.exists()" because "member" is null
	at org.eclipse.jdt.internal.corext.refactoring.RefactoringAvailabilityTesterCore.isMoveStaticAvailable(RefactoringAvailabilityTesterCore.java:124)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.isMoveStaticMemberAvailable(RefactorProposalUtility.java:235)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.getMoveRefactoringProposals(RefactorProposalUtility.java:143)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getMoveRefactoringProposals(RefactorProcessor.java:206)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getProposals(RefactorProcessor.java:137)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:204)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:753)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
```

Typing `main` to generate a main command will also cause another NPE:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IType.getField(String)" because the return value of "org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.getJavaElement()" is null
	at org.eclipse.jdt.internal.javac.dom.JavacVariableBinding.getJavaElement(JavacVariableBinding.java:131)
	at org.eclipse.jdt.ls.core.internal.handlers.GenerateConstructorsHandler.checkConstructorStatus(GenerateConstructorsHandler.java:109)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getGenerateConstructorsAction(SourceAssistProcessor.java:517)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getSourceActionCommands(SourceAssistProcessor.java:132)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:240)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:753)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
```

**Comment by mickaelistria** [comment]
I cannot reproduce. Is it still happening?

**Comment by mickaelistria** [comment]
Cannot reproduce
