### ISSUE TITLE
[completion] NPE when completing without a prefix

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdtls/eclipse-jdt-core-incubator#634]
```
public class App {
    public void foo() {
       $
     }
}
```

Invoke code completion at position of `$`.

```
Cannot read the array length because "value" is null
java.lang.NullPointerException: Cannot read the array length because "value" is null
	at java.base/java.lang.String.<init>(String.java:283)
	at java.base/java.lang.String.valueOf(String.java:4573)
	at org.eclipse.jdt.internal.corext.template.java.CompilationUnitCompletion.accept(CompilationUnitCompletion.java:777)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.eclipse.jdt.internal.codeassist.DOMCompletionEngine.run(DOMCompletionEngine.java:360)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:500)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:494)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:484)
	at org.eclipse.jdt.internal.corext.template.java.JavaContextCore.getCompletion(JavaContextCore.java:328)
	at org.eclipse.jdt.internal.corext.template.java.JavaContextCore.getIterables(JavaContextCore.java:404)
	at org.eclipse.jdt.internal.corext.template.java.AbstractJavaContextTypeCore$IterableType.getVariablesInContextScope(AbstractJavaContextTypeCore.java:183)
	at org.eclipse.jdt.internal.corext.template.java.AbstractJavaContextTypeCore$AbstractIterableType.resolve(AbstractJavaContextTypeCore.java:140)
	at org.eclipse.jface.text.templates.TemplateContextType.resolve(TemplateContextType.java:276)
	at org.eclipse.jface.text.templates.TemplateContextType.resolve(TemplateContextType.java:243)
	at org.eclipse.jdt.internal.corext.template.java.JavaContextCore.evaluate(JavaContextCore.java:157)
	at org.eclipse.jdt.ls.core.internal.contentassist.SnippetCompletionProposal.evaluateGenericTemplate(SnippetCompletionProposal.java:444)
	at org.eclipse.jdt.ls.core.internal.contentassist.SnippetCompletionProposal.getGenericSnippets(SnippetCompletionProposal.java:380)
	at org.eclipse.jdt.ls.core.internal.contentassist.SnippetCompletionProposal.getSnippets(SnippetCompletionProposal.java:219)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:298)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.completion(JDTLanguageServer.java:623)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:272)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by gayanper** [comment]
@mickaelistria can you give me access to assigned issues, so I can assign all code completion issues I find to my self to fix them ?

**Comment by gayanper** [comment]
Another observed exception with same symptom 

```
Cannot invoke "org.eclipse.jdt.core.dom.ITypeBinding.isRecovered()" because "binding" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.dom.ITypeBinding.isRecovered()" because "binding" is null
	at org.eclipse.jdt.internal.codeassist.DOMCompletionEngineRecoveredNodeScanner$SuitableNodeVisitor.visit(DOMCompletionEngineRecoveredNodeScanner.java:119)
	at org.eclipse.jdt.core.dom.SimpleType.accept0(SimpleType.java:189)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3391)
	at org.eclipse.jdt.core.dom.VariableDeclarationStatement.accept0(VariableDeclarationStatement.java:252)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3414)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3343)
	at org.eclipse.jdt.internal.codeassist.DOMCompletionEngineRecoveredNodeScanner.findClosestSuitableBinding(DOMCompletionEngineRecoveredNodeScanner.java:202)
	at org.eclipse.jdt.internal.codeassist.DOMCompletionEngine.run(DOMCompletionEngine.java:347)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:500)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:489)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:287)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.completion(JDTLanguageServer.java:623)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:272)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by mickaelistria** [comment]
This seems outdated.
