### ISSUE TITLE
NPE with JavacProblemConverter

### ISSUE THREAD

**Issue by testforstephen** [eclipse-jdtls/eclipse-jdt-core-incubator#790]
Opening the project https://github.com/apache/struts.git with Javac bits, got the NPE as follows.

```
!MESSAGE compilation failed
!STACK 0
java.lang.NullPointerException: Cannot invoke "com.sun.source.util.TreePath.getParentPath()" because "diagnosticPath" is null
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.getDiagnosticPosition(JavacProblemConverter.java:245)
	at org.eclipse.jdt.internal.javac.JavacProblemConverter.createJavacProblem(JavacProblemConverter.java:109)
	at org.eclipse.jdt.internal.javac.JavacCompiler.lambda$compile$0(JavacCompiler.java:74)
	at jdk.compiler/com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:741)
	at jdk.compiler/com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:722)
	at jdk.compiler/com.sun.tools.javac.util.Log.report(Log.java:675)
	at jdk.compiler/com.sun.tools.javac.util.AbstractLog.error(AbstractLog.java:116)
	at jdk.compiler/com.sun.tools.javac.comp.Check.checkOverride(Check.java:2194)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1019)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:957)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:674)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:748)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5638)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5526)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5350)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:5287)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1355)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:977)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:897)
	at org.eclipse.jdt.internal.javac.JavacCompiler.compile(JavacCompiler.java:162)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:414)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:211)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:345)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:286)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment]
This was most likely fixed with https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/commit/b78227ff51ee134f1f19631167fad8995a7c79c5 , merged ~8 hours ago. Can you please verify with latest bits?

**Comment by testforstephen** [comment]
yes, this NPE disappears with the latest Javac bits. Closing it.
