### ISSUE TITLE
java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)

### ISSUE THREAD

**Issue by testforstephen** [eclipse-jdtls/eclipse-jdt-core-incubator#791]
```
!ENTRY org.eclipse.m2e.apt.core 4 0 2024-09-04 13:51:44.745
!MESSAGE Error while reading artifact JARs.
!STACK 0
java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1848)
	at java.base/java.util.zip.ZipFile$Source.checkZip64ExtraFieldValues(ZipFile.java:1377)
	at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1337)
	at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1255)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1787)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1562)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1525)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:744)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:254)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:282)
	at org.eclipse.m2e.apt.internal.utils.AnnotationServiceLocator.getAptServiceEntries(AnnotationServiceLocator.java:90)
	at org.eclipse.m2e.apt.internal.utils.ProjectUtils.containsAptProcessors(ProjectUtils.java:264)
	at org.eclipse.m2e.apt.internal.AbstractAptConfiguratorDelegate.configureProject(AbstractAptConfiguratorDelegate.java:141)
	at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.lambda$0(AbstractAptProjectConfigurator.java:95)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
	at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.configure(AbstractAptProjectConfigurator.java:88)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:123)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:503)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:497)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:278)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$1(ProjectConfigurationManager.java:165)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:138)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:129)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:242)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:164)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:126)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:277)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This error happens at resolving the dependency jar `org/aspectj/aspectjweaver/1.8.10/aspectjweaver-1.8.10.jar`.  The sample project is https://github.com/wycm/zhihu-crawler.git. It works when  opening it with the marketplace vscode-java extension (launched with Java 17), but got the error above with Javac bits (launched with Java 23). This should be a Java 23 compatibility issue because if I set Java 23 to launch the marketplace vscode-java, it also got the same exception.

**Comment by mickaelistria** [comment]
Can you please try running the marketplace vscode-java with Java 23 ? If this fails the same way, then the issue is not related to any change we've done here should be addressed to m2e or JDT.

**Comment by testforstephen** [comment]
> Can you please try running the marketplace vscode-java with Java 23

already did it. It failed with the same exception when starting the marketplace vscode-java on JDK 23.

**Comment by mickaelistria** [comment]
Sorry, I had missed this detail. There is nothing we can really fix here I guess. Please report it to m2e then.

**Comment by testforstephen** [comment]
Opened an issue at m2e repo. https://github.com/eclipse-m2e/m2e-core/issues/1823

**Comment by mickaelistria** [comment]
Closing it here as there is nothing we can do from this codebase.
