### ISSUE TITLE
DOM completion doesn't provide relevant results

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#891]
Testing on Lemminx's CMRelaxNGDocument.java, completing `targetSchema.` at or below the following [position](https://github.com/eclipse/lemminx/blob/main/org.eclipse.lemminx/src/main/java/com/thaiopensource/relaxng/pattern/CMRelaxNGDocument.java#L309), DOM-based completion behaves weirdly:

- `locator` field doesn't exist, shouldn't be returned 
<img width="683" alt="Screenshot 2024-10-16 at 16 58 04" src="https://github.com/user-attachments/assets/65a85143-8ef8-423d-9a4f-084f44c46e9b">

- `offsetAt` method is not proposed
<img width="820" alt="Screenshot 2024-10-16 at 16 59 01" src="https://github.com/user-attachments/assets/ca0c7359-3409-4811-9154-8dcd06a2902a">

**Comment by fbricon** [comment]
locator is a method parameter, systemId is a method variable, they should not be proposed when completing on `targetSchema.`

**Comment by fbricon** [comment]
I just tried the latest vscode-java pre-relrease build, and it seems it's even worse now, `targetSchema.` completion returns an empty array now

**Comment by datho7561** [comment]
I'll give it another shot in vscode and see what's happening

**Comment by datho7561** [comment]
~~I think the root cause is that is that our DOM conversion code is trying to create `targetSchema.int`.~~

~~update: nope, it works in Eclipse but not VS Code, I'll have to debug to figure this out.~~

Update: It works in Eclipse because the fix is on my filesystem uncommited :facepalm: time to open that one as a PR  :zany_face:

However the current blocker for me seems to be a bad downcast from Intellicode:

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2024-11-04 13:47:06.439
!MESSAGE Problem with codeComplete for file:///home/davthomp/Documents/Projects/lemminx/org.eclipse.lemminx/src/main/java/com/thaiopensource/relaxng/pattern/CMRelaxNGDocument.java
!STACK 0
java.lang.ClassCastException: class org.eclipse.jdt.internal.codeassist.DOMCompletionContext cannot be cast to class org.eclipse.jdt.internal.codeassist.InternalCompletionContext (org.eclipse.jdt.internal.codeassist.DOMCompletionContext and org.eclipse.jdt.internal.codeassist.InternalCompletionContext are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5506402)
	at com.microsoft.jdtls.intellicode.core.ModelBasedRankingProvider.rank(ModelBasedRankingProvider.java:52)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getAggregatedRankingResult(CompletionProposalRequestor.java:363)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:262)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:258)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:296)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.completion(JDTLanguageServer.java:626)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by datho7561** [comment]
Just for completion sake, another important part of the fix was https://github.com/redhat-developer/vscode-java/commit/6292a4c29690bbae7280b2027a87ce7663d74e96
