### ISSUE TITLE
StackOverflow when trying to build eclipse-jdt-core-incubator

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#912]
Here is the StackOverflow:

```
!ENTRY org.eclipse.jdt.core 4 0 2024-10-29 16:41:47.039
!MESSAGE compilation failed
!STACK 0
java.lang.StackOverflowError
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1082)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1074)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSuperType(Types.java:1301)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1083)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1074)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSuperType(Types.java:1301)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1083)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1074)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSuperType(Types.java:1301)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1083)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1074)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSuperType(Types.java:1301)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1083)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1074)
	at jdk.compiler/com.sun.tools.javac.code.Types.isSuperType(Types.java:1301)
...
```

**Comment by datho7561** [comment]
This appears to be coming from one of the test suites, so perhaps it's one of the test files.

**Comment by mickaelistria** [comment]
This wasn't reproduced for some time. Let's close (and reopen if necessary later)
