### ISSUE TITLE
Error building with Javac

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#945]
In my workspace I have
* org.eclipse.jdt.core
* org.eclipse.jdt.core.javac
* org.eclipse.jdt.tests.javac
* org.eclipse.jdt.tests.model

When building them (after clean), the .class are not generated, and so far, no error is reported.
I have added logging and can see that exception
```
!ENTRY org.eclipse.jdt.core 4 0 2024-11-13 17:38:41.866
!MESSAGE class com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to class com.sun.tools.javac.code.Symbol$MethodSymbol (com.sun.tools.javac.code.Symbol$ClassSymbol and com.sun.tools.javac.code.Symbol$MethodSymbol are in module jdk.compiler of loader 'app')
!STACK 0
java.lang.ClassCastException: class com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to class com.sun.tools.javac.code.Symbol$MethodSymbol (com.sun.tools.javac.code.Symbol$ClassSymbol and com.sun.tools.javac.code.Symbol$MethodSymbol are in module jdk.compiler of loader 'app')
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:669)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1857)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:443)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitVarDef(TransTypes.java:488)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1063)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:144)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:961)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:464)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:855)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:443)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:983)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1609)
	at org.eclipse.jdt.internal.javac.JavacCompiler$2.desugar(JavacCompiler.java:158)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1464)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1572)
	at org.eclipse.jdt.internal.javac.JavacCompiler$2.desugar(JavacCompiler.java:158)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1464)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1572)
	at org.eclipse.jdt.internal.javac.JavacCompiler$2.desugar(JavacCompiler.java:158)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1464)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1572)
	at org.eclipse.jdt.internal.javac.JavacCompiler$2.desugar(JavacCompiler.java:158)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1464)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:977)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:897)
	at org.eclipse.jdt.internal.javac.JavacCompiler.compile(JavacCompiler.java:182)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:441)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:250)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:118)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:317)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:220)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
A breakpoint there allows to inspect the `javacProblems`:
```
{SourceFile[/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AbstractJavaModelTests.java]=[Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.core.search does not exist, Pb(2) package org.eclipse.jdt.internal.core.search does not exist, Pb(2) package org.eclipse.jdt.internal.core.util does not exist, Pb(73) runFinalization() in java.lang.System has been deprecated and marked for removal, Pb(73) runFinalization() in java.lang.System has been deprecated and marked for removal], SourceFile[/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/APIDocumentationTests.java]=[Pb(2) cannot find symbol
  symbol:   class JavaCore
  location: package org.eclipse.jdt.core, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist, Pb(2) package org.eclipse.jdt.core.dom does not exist], SourceFile[/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/AbstractASTTests.java]=[Pb(2) cannot find symbol
  symbol:   class IBuffer
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class IClassFile
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class IJavaProject
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class IProblemRequestor
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class JavaCore
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: package org.eclipse.jdt.core, Pb(2) cannot find symbol
  symbol:   class WorkingCopyOwner
  location: package org.eclipse.jdt.core, Pb(2) package org.eclipse.jdt.internal.core.dom does not exist, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTParser
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IClassFile
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IClassFile
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ICompilationUnit
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ASTNode
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IVariableBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IMethodBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IJavaProject
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class IMethodBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class ITypeBinding
  location: class org.eclipse.jdt.core.tests.dom.AbstractASTTests, Pb(2) cannot find symbol
  symbol:   class JavaModelException
  location: class org.eclipse.jdt.core.tests.dom....
SourceFile[/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/ModifyingResourceTests.java]=[Pb(2) package org.eclipse.jdt.internal.core does not exist, Pb(2) package org.eclipse.jdt.internal.core does not exist, Pb(2) package org.eclipse.jdt.internal.core does not exist]
```
It looks like trying to continue compilation in case of problems without intermediary fixes is not likely to succeed.

**Comment by mickaelistria** [comment]
There are some underlying errors preventing to build even the single `org.eclipse.jdt.core` bundle:
Digging with a debugger, one deeper cause is:
```
com.sun.tools.javac.code.ClassFinder$BadClassFile: bad class file: /H/java.base/module-info.sig
  unable to access file: java.nio.channels.ClosedChannelException
  Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by mickaelistria** [comment]
The issue in TransType might is covered by #936

**Comment by mickaelistria** [comment]
Should be fixed now.
