### ISSUE TITLE
NPE DOMCodeSelector.findTypeInIndex(DOMCodeSelector.java:616)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdtls/eclipse-jdt-core-incubator#988]
```
java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "simpleName" is null
	at org.eclipse.jdt.internal.codeassist.DOMCodeSelector.findTypeInIndex(DOMCodeSelector.java:616)
	at org.eclipse.jdt.internal.codeassist.DOMCodeSelector.codeSelect(DOMCodeSelector.java:406)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:469)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:461)
```

**Comment by mickaelistria** [comment]
Looks like an outdated version
